### ISSUE TITLE
Video_Output_HDMI

### ISSUE THREAD

**Issue by huangazazaz** [VSOPwsy/LoongArch-Processing-System#3]

**Comment by VSOPwsy** [comment]
这个模块里的Stream FIFO只需要能存得下一行像素就够了，HDMI协议是一行一行输出像素的，读DDR的速度应该远快于HDMI输出的速度。
另外需要一个PLL来产生时钟，具体要参考HDMI协议。可以先只支持1920*1080@60（148.5M时钟），最后再做参数化。网上也有可能找到现成的转HDMI时序的模块，能直接用最好，但是要找来源靠谱的。
![20190922001821877](https://github.com/VSOPwsy/LoongArch-Processing-System/assets/131957351/3760b1dc-dead-4c1e-83c6-e92e532e0765)
